### ISSUE TITLE
Error when start a cluster. 

### ISSUE THREAD

**Issue by xiongjie494** [jtriley/StarCluster#590]
---------- SYSTEM INFO ----------
StarCluster: 0.95.6
Python: 2.7.12 (default, Jul  1 2016, 15:12:24)  [GCC 5.4.0 20160609]
Platform: Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
boto: 2.42.0
paramiko: 2.0.2
Crypto: 2.6.1

---------- CRASH DETAILS ----------
Command: starcluster start mycluster

2016-09-06 16:07:50,588 PID: 21253 config.py:567 - DEBUG - Loading config
2016-09-06 16:07:50,588 PID: 21253 config.py:138 - DEBUG - Loading file: /home/steve/.starcluster/config
2016-09-06 16:07:50,590 PID: 21253 awsutils.py:75 - DEBUG - creating self._conn w/ connection_authenticator kwargs = {'proxy_user': None, 'proxy_pass': None, 'proxy_port': None, 'proxy': None, 'is_secure': True, 'path': '/', 'region': None, 'validate_certs': True, 'port': None}
2016-09-06 16:07:51,156 PID: 21253 start.py:224 - INFO - Using default cluster template: smallcluster
2016-09-06 16:07:51,156 PID: 21253 cluster.py:1803 - INFO - Validating cluster template settings...
2016-09-06 16:07:51,978 PID: 21253 sshutils.py:860 - DEBUG - rsa private key fingerprint (/home/steve/.ssh/mykey.rsa): 6e:78:d8:eb:33:1c:7f:77:7f:97:72:fd:1f:f9:e5:78:cd:10:66:76
2016-09-06 16:07:52,120 PID: 21253 cluster.py:759 - DEBUG - existing nodes: {}
2016-09-06 16:07:52,121 PID: 21253 cluster.py:775 - DEBUG - returning self._nodes = []
2016-09-06 16:07:52,350 PID: 21253 cluster.py:1130 - DEBUG - Launch map: node001 (ami: ami-3393a45a, type: m1.small)...
2016-09-06 16:07:52,361 PID: 21253 cluster.py:911 - DEBUG - Userdata size in KB: 0.46
2016-09-06 16:07:52,361 PID: 21253 cluster.py:1821 - INFO - Cluster template settings are valid
2016-09-06 16:07:52,361 PID: 21253 cluster.py:1641 - INFO - Starting cluster...
2016-09-06 16:07:52,362 PID: 21253 cluster.py:1157 - INFO - Launching a 2-node cluster...
2016-09-06 16:07:52,362 PID: 21253 cluster.py:1130 - DEBUG - Launch map: node001 (ami: ami-3393a45a, type: m1.small)...
2016-09-06 16:07:52,362 PID: 21253 cluster.py:1182 - DEBUG - Launching master (ami: ami-3393a45a, type: m1.small)
2016-09-06 16:07:52,362 PID: 21253 cluster.py:1182 - DEBUG - Launching node001 (ami: ami-3393a45a, type: m1.small)
2016-09-06 16:07:52,464 PID: 21253 awsutils.py:295 - INFO - Creating security group @sc-mycluster...
2016-09-06 16:07:54,937 PID: 21253 cluster.py:911 - DEBUG - Userdata size in KB: 0.46
2016-09-06 16:07:55,155 PID: 21253 cluster.py:759 - DEBUG - existing nodes: {}
2016-09-06 16:07:55,155 PID: 21253 cluster.py:775 - DEBUG - returning self._nodes = []
2016-09-06 16:07:55,275 PID: 21253 awsutils.py:495 - DEBUG - Forcing delete_on_termination for AMI: ami-3393a45a
2016-09-06 16:07:56,254 PID: 21253 cluster.py:968 - INFO - Reservation:r-0b3b842d595359d79
2016-09-06 16:07:56,254 PID: 21253 awsutils.py:557 - INFO - Waiting for instances to propagate...
2016-09-06 16:07:56,555 PID: 21253 cluster.py:1442 - INFO - Waiting for cluster to come up... (updating every 30s)
2016-09-06 16:07:56,793 PID: 21253 cluster.py:1399 - INFO - Waiting for all nodes to be in a 'running' state...
2016-09-06 16:07:57,016 PID: 21253 cluster.py:759 - DEBUG - existing nodes: {}
2016-09-06 16:07:57,017 PID: 21253 cluster.py:767 - DEBUG - adding node i-02f10949eaf806be8 to self._nodes list
2016-09-06 16:07:57,816 PID: 21253 cluster.py:767 - DEBUG - adding node i-0682d7cf5db6cac65 to self._nodes list
2016-09-06 16:07:58,305 PID: 21253 cluster.py:775 - DEBUG - returning self._nodes = [<Node: master (i-0682d7cf5db6cac65)>, <Node: node001 (i-02f10949eaf806be8)>]
2016-09-06 16:08:29,019 PID: 21253 cluster.py:759 - DEBUG - existing nodes: {u'i-0682d7cf5db6cac65': <Node: master (i-0682d7cf5db6cac65)>, u'i-02f10949eaf806be8': <Node: node001 (i-02f10949eaf806be8)>}
2016-09-06 16:08:29,020 PID: 21253 cluster.py:762 - DEBUG - updating existing node i-02f10949eaf806be8 in self._nodes
2016-09-06 16:08:29,021 PID: 21253 cluster.py:762 - DEBUG - updating existing node i-0682d7cf5db6cac65 in self._nodes
2016-09-06 16:08:29,021 PID: 21253 cluster.py:775 - DEBUG - returning self._nodes = [<Node: master (i-0682d7cf5db6cac65)>, <Node: node001 (i-02f10949eaf806be8)>]
2016-09-06 16:08:29,021 PID: 21253 cluster.py:1427 - INFO - Waiting for SSH to come up on all nodes...
2016-09-06 16:08:29,184 PID: 21253 cluster.py:759 - DEBUG - existing nodes: {u'i-0682d7cf5db6cac65': <Node: master (i-0682d7cf5db6cac65)>, u'i-02f10949eaf806be8': <Node: node001 (i-02f10949eaf806be8)>}
2016-09-06 16:08:29,184 PID: 21253 cluster.py:762 - DEBUG - updating existing node i-02f10949eaf806be8 in self._nodes
2016-09-06 16:08:29,185 PID: 21253 cluster.py:762 - DEBUG - updating existing node i-0682d7cf5db6cac65 in self._nodes
2016-09-06 16:08:29,185 PID: 21253 cluster.py:775 - DEBUG - returning self._nodes = [<Node: master (i-0682d7cf5db6cac65)>, <Node: node001 (i-02f10949eaf806be8)>]
2016-09-06 16:08:29,209 PID: 21253 threadpool.py:168 - DEBUG - unfinished_tasks = 2
2016-09-06 16:08:29,381 PID: 21253 sshutils.py:87 - DEBUG - loading private key /home/steve/.ssh/mykey.rsa
2016-09-06 16:08:29,668 PID: 21253 sshutils.py:87 - DEBUG - loading private key /home/steve/.ssh/mykey.rsa
2016-09-06 16:08:30,214 PID: 21253 cli.py:284 - ERROR - error occurred in job (id=master): 'EntryPoint' object has no attribute 'resolve'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 75, in run
    r = self.method(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cluster.py", line 1429, in <lambda>
    self.pool.map(lambda n: n.wait(interval=self.refresh_interval), nodes,
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1019, in wait
    while not self.is_up():
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1025, in is_up
    if not self.is_ssh_up():
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1010, in is_ssh_up
    return self.ssh.transport is not None
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1070, in ssh
    private_key=self.key_location)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 78, in __init__
    self._pkey = self.load_private_key(private_key, private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 89, in load_private_key
    pkey = self._load_rsa_key(private_key, private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 184, in _load_rsa_key
    passphrase=private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 816, in get_rsa_key
    password=passphrase)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/pkey.py", line 217, in from_private_key
    key = cls(file_obj=file_obj, password=password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 42, in __init__
    self._from_private_key(file_obj, password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 168, in _from_private_key
    self._decode_key(data)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 173, in _decode_key
    data, password=None, backend=default_backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.5-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.5-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

error occurred in job (id=node001): 'EntryPoint' object has no attribute 'resolve'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 75, in run
    r = self.method(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cluster.py", line 1429, in <lambda>
    self.pool.map(lambda n: n.wait(interval=self.refresh_interval), nodes,
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1019, in wait
    while not self.is_up():
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1025, in is_up
    if not self.is_ssh_up():
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1010, in is_ssh_up
    return self.ssh.transport is not None
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1070, in ssh
    private_key=self.key_location)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 78, in **init**
    self._pkey = self.load_private_key(private_key, private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 89, in load_private_key
    pkey = self._load_rsa_key(private_key, private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 184, in _load_rsa_key
    passphrase=private_key_pass)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 816, in get_rsa_key
    password=passphrase)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/pkey.py", line 217, in from_private_key
    key = cls(file_obj=file_obj, password=password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 42, in __init__
    self._from_private_key(file_obj, password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 168, in _from_private_key
    self._decode_key(data)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-2.0.2-py2.7.egg/paramiko/rsakey.py", line 173, in _decode_key
    data, password=None, backend=default_backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.5-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.5-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by vasisht** [comment]
This looks like you're running an old version of setuptools and/or distribute. It should go away if you upgrade setuptools to the latest version.

**Comment by xiongjie494** [comment]
Thank you very much. It works after I upgrade setuptools to 26.1.1.

**Comment by apratim88** [comment]
I was getting the same error. 
How do  I upgrade setuptools to 26.1.1 ?
Sorry I am new to this.

**Comment by vasisht** [comment]
If you're on Ubuntu or OS X:
`sudo pip install -U setuptools`
